/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Footer_navigation: typeof import('./src/components/general/Footer_navigation.vue')['default']
    Home_page: typeof import('./src/components/custom/home_page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Side_multilevel_menu: typeof import('./src/components/general/side_multilevel_menu.vue')['default']
    Top_navigation_bar: typeof import('./src/components/general/Top_navigation_bar.vue')['default']
  }
}
